lang: ko
title: Duchang's DEV WIKI
author:
  name: duchangkim
  email: duchang.dev@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  개발 관련 지식을 공부하고 쌓아두는 위키 입니다. 모든 글은 미완성일 수 있으며, 계속해서 업데이트 됩니다.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:
    github:  duchangkim
    instagram: ___duchi
    # linkedin: duchangkim

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up

#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# syntax highlight
markdown: kramdown
highlighter: rouge